<?php

namespace Tests\Unit;

use Dev\Kernel\Commands\GDriveMirrorSync;
use PHPUnit\Framework\TestCase;

/**
 * Bảo vệ 2 helper thuần đứng sau atomic write-then-rename thêm vào GDriveMirrorSync
 * (2026-07-19): atomicTempPath() và isOwnAtomicTempFilename(). Trước bản này, PHP ghi THẲNG
 * vào file đích (khác bản Go) — crash/mất mạng/rút ổ giữa chừng để lộ 1 file CỤT ngay tại path
 * thật cho tới lần sync kế tiếp mới tự chữa. Xem docblock đầu GDriveMirrorSync.php mục 3/4 và
 * `tools/gdrive-mirror-cli/internal/mirror/download.go::tempDownloadPath()` (bản Go tương ứng).
 *
 * Pure/static (không đụng $this/facade) nên test không cần boot Laravel — cùng convention
 * GDriveErrorClassificationTest.php / GDriveLocalPathTest.php. Phần I/O thật (mở file tạm,
 * rename, quét dọn rác — atomicPutContents()/atomicWriteStream()/cleanupStaleAtomicTempFiles())
 * là instance method dùng Log facade nên không unit-test ở đây; 2 hàm thuần dưới đây là phần
 * quyết định TÍNH ĐÚNG ĐẮN của cơ chế (tên tạm cố định độ dài + không xoá nhầm file người dùng).
 */
class GDriveAtomicWriteTest extends TestCase
{
    // ───────────────────────── atomicTempPath() ─────────────────────────

    public function test_temp_path_has_fixed_length_regardless_of_target_name_length(): void
    {
        $short = GDriveMirrorSync::atomicTempPath('/data/a.pdf', 'abc12345');
        $long = GDriveMirrorSync::atomicTempPath(
            '/data/' . str_repeat('Báo cáo tài chính rất dài ', 20) . '.pdf',
            'abc12345'
        );

        // Chỉ so basename — 2 target khác thư mục/độ dài nhưng cùng runId phải ra tên tạm
        // CÙNG ĐỘ DÀI BYTE (bất kể tên đích ngắn hay dài cỡ nào).
        self::assertSame(strlen(basename($short)), strlen(basename($long)));
        // Đúng công thức: '.' + 8 hex + '-' + 8 hex + '.tmp' = 1+8+1+8+4 = 22 byte.
        self::assertSame(22, strlen(basename($short)));
    }

    public function test_temp_path_is_in_same_directory_as_target(): void
    {
        $target = '/Volumes/WD-DATA1/OneDrive/Projects/Client A/report.docx';
        $tmp = GDriveMirrorSync::atomicTempPath($target, 'runid001');

        self::assertSame(dirname($target), dirname($tmp));
    }

    public function test_temp_path_basename_matches_own_pattern(): void
    {
        $tmp = GDriveMirrorSync::atomicTempPath('/data/whatever.pdf', 'deadbeef');

        self::assertTrue(GDriveMirrorSync::isOwnAtomicTempFilename(basename($tmp)));
    }

    public function test_different_target_paths_produce_different_temp_names(): void
    {
        $a = GDriveMirrorSync::atomicTempPath('/data/a.pdf', 'runid001');
        $b = GDriveMirrorSync::atomicTempPath('/data/b.pdf', 'runid001');

        self::assertNotSame($a, $b);
    }

    public function test_same_target_and_run_id_are_deterministic(): void
    {
        $a = GDriveMirrorSync::atomicTempPath('/data/a.pdf', 'runid001');
        $b = GDriveMirrorSync::atomicTempPath('/data/a.pdf', 'runid001');

        self::assertSame($a, $b);
    }

    public function test_temp_path_root_directory_target(): void
    {
        // dirname('/a.pdf') === '/' — không được lộ path dạng '//..." (double slash).
        $tmp = GDriveMirrorSync::atomicTempPath('/a.pdf', 'runid001');

        self::assertSame('/', dirname($tmp));
        self::assertStringStartsWith('/.', $tmp);
    }

    // ───────────────────────── isOwnAtomicTempFilename() ─────────────────────────

    public function test_recognizes_own_generated_names(): void
    {
        foreach (['a.pdf', 'b/c.docx', '/x/y/z.mp4'] as $target) {
            $tmp = GDriveMirrorSync::atomicTempPath($target, 'aa112233');
            self::assertTrue(
                GDriveMirrorSync::isOwnAtomicTempFilename(basename($tmp)),
                "expected own pattern to match for target={$target}"
            );
        }
    }

    public static function nonMatchingNameProvider(): array
    {
        return [
            'ordinary pdf' => ['bao cao.pdf'],
            'ordinary hidden file' => ['.hidden'],
            'no leading dot, has .tmp ext' => ['abc.tmp'],
            'extra real extension after .tmp' => ['.12345678-abcdef01.tmp.pdf'],
            'run id segment too short' => ['.1234567-abcdef01.tmp'],
            'hash segment too short' => ['.12345678-abcdef0.tmp'],
            'uppercase hex not generated by hash()/uniqid()' => ['.ABCDEF01-ABCDEF01.tmp'],
            'missing dash separator' => ['.12345678abcdef01.tmp'],
            'empty string' => [''],
            'just dot tmp' => ['.tmp'],
            'legacy suffix scheme (target-name + .tmp-runId)' => ['report.pdf.tmp-abcdef01'],
        ];
    }

    /**
     * @dataProvider nonMatchingNameProvider
     */
    public function test_rejects_names_that_do_not_match_own_pattern(string $basename): void
    {
        self::assertFalse(GDriveMirrorSync::isOwnAtomicTempFilename($basename));
    }
}
